var tickers = [
  ['AAL', 'American Airlines'],
  ['AAPL', 'Apple'],
  ['ACB', 'Aurora Cannabis'],
  ['AMD', 'AMD'],
  ['AMZN', 'Amazon'],
  ['APHA', 'Aphria'],
  ['ATVI', 'Activision Blizzard'],
  ['BA', 'Boeing'],
  ['BABA', 'Alibaba'],
  ['BAC', 'Bank of America'],
  ['BYND', 'Beyond Meat'],
  ['CCL', 'Carnival'],
  ['DAL', 'Delta Airlines'],
  ['DIS', 'Disney'],
  ['F', 'Ford Motor'],
  ['FB', 'Facebook'],
  ['FIT', 'Fitbit'],
  ['GE', 'GE'],
  ['GILD', 'Gilead Sciences'],
  ['GM', 'GM'],
  ['GOOGL', 'Alphabet Class A'],
  ['INTC', 'Intel'],
  ['JNJ', 'Johnson & Johnson'],
  ['JPM', 'JPMoragn Chase'],
  ['KO', 'Coca-Cola'],
  ['KODK', 'Kodak'],
  ['LUV', 'Southwest'],
  ['LYFT', 'Lyft'],
  ['MRNA', 'Moderna'],
  ['MSFT', 'Microsoft'],
  ['NFLX', 'Netflix'],
  ['NIO', 'Nio'],
  ['NKE', 'Nike'],
  ['NOK', 'Nokia'],
  ['NTDOY', 'Nintendo'],
  ['NVDA', 'NIVIDIA'],
  ['PFE', 'Pfizer'],
  ['PTON', 'Peloton'],
  ['PYPL', 'PayPal'],
  ['SBUX', 'Starbucks'],
  ['SNAP', 'Snapchat'],
  ['SNE', 'Sony'],
  ['SPCE', 'Virgin Galactic Holdings'],
  ['SPY', 'SPDR S&P 500 ETF'],
  ['SQ', 'Sqaure'],
  ['T', 'AT&T'],
  ['TCEHY', 'Tencent'],
  ['TSLA', 'Tesla'],
  ['TWTR', 'Twitter'],
  ['UAL', 'United Airlines'],
  ['UBER', 'Uber'],
  ['USO', 'United States Oil Fund'],
  ['V', 'Visa'],
  ['VOO', 'Vanguard S&P 500 EFT'],
  ['WFC', 'Wells Fargo'],
  ['WKHS', 'Workhorse'],
  ['WMT', 'Walmart'],
  ['WORK', 'Slack'],
  ['XOM', 'Exxon Mobil'],
  ['ZM', 'Zoom'],
  ['ZNGA', 'Zynga']
];

export default tickers;